development:
  adapter: mysql2
  database: seeyouaround
  username: root
  password: jhc23
  host: localhost
  pool: 5
  timeout: 5000
  socket: /run/mysqld/mysqld.sock

test:
  adapter: mysql2
  database: heyorder_development
  username: root
  password: xxx
  host: localhost
  pool: 5
  timeout: 5000
  socket: /run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: seeyouaround
  username: root
  password: xxx
  host: localhost
  pool: 5
  timeout: 5000
  socket: /run/mysqld/mysqld.sock